//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plex.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_9x_pointer {
            get {
                object obj = ResourceManager.GetObject("cursor_9x_pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon0 {
            get {
                object obj = ResourceManager.GetObject("fileicon0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon1 {
            get {
                object obj = ResourceManager.GetObject("fileicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon10 {
            get {
                object obj = ResourceManager.GetObject("fileicon10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon11 {
            get {
                object obj = ResourceManager.GetObject("fileicon11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon12 {
            get {
                object obj = ResourceManager.GetObject("fileicon12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon13 {
            get {
                object obj = ResourceManager.GetObject("fileicon13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon14 {
            get {
                object obj = ResourceManager.GetObject("fileicon14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon15 {
            get {
                object obj = ResourceManager.GetObject("fileicon15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon16 {
            get {
                object obj = ResourceManager.GetObject("fileicon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon17 {
            get {
                object obj = ResourceManager.GetObject("fileicon17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon18 {
            get {
                object obj = ResourceManager.GetObject("fileicon18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon19 {
            get {
                object obj = ResourceManager.GetObject("fileicon19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon2 {
            get {
                object obj = ResourceManager.GetObject("fileicon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon3 {
            get {
                object obj = ResourceManager.GetObject("fileicon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon4 {
            get {
                object obj = ResourceManager.GetObject("fileicon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon5 {
            get {
                object obj = ResourceManager.GetObject("fileicon5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon6 {
            get {
                object obj = ResourceManager.GetObject("fileicon6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon7 {
            get {
                object obj = ResourceManager.GetObject("fileicon7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon8 {
            get {
                object obj = ResourceManager.GetObject("fileicon8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileicon9 {
            get {
                object obj = ResourceManager.GetObject("fileicon9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileiconcf {
            get {
                object obj = ResourceManager.GetObject("fileiconcf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileiconsaa {
            get {
                object obj = ResourceManager.GetObject("fileiconsaa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [        ///	&quot;english&quot;        ///	&quot;deutsch - in beta&quot;        ///]
        ///.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*        /// * Project: Plex        /// *         /// * Copyright (c) 2017 Watercolor Games. All rights reserved. For internal use only.        /// *         ///        ///        ///        ///        ///        ///        /// *         /// * The above copyright notice and this permission notice shall be included in all        /// * copies or substantial portions of the Software.        /// *         /// * THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR        /// * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,        /// * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE        /// * AUTHORS OR COPYRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pywintemplate {
            get {
                return ResourceManager.GetString("pywintemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	&quot;verbose - joke lang - in beta&quot;
        ///].
        /// </summary>
        internal static string secretlang {
            get {
                return ResourceManager.GetString("secretlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*        /// * THIS IS AN EXAMPLE FILE        /// *        /// * Any Shiftorium upgrades placed in here won&apos;t be recognized by the main Plex frontend        /// * (Plex.WinForms). It uses its own Shiftorium definition file found in its Resources.        /// */        ///        ///[        ///	{        ///		Name: &quot;MUD Fundamentals&quot;,        ///		Cost: 50,        ///		Description: &quot;Some basic commands for the terminal that&apos;ll help you out in the multi-user domain.&quot;,        ///		Dependencies: null        ///	},        ///	{        ///		Name: &quot;WM 4 Windows&quot;,        ///		Cost: 150,        ///		Description: &quot;Display up to 4 simultaneous windows on-screen in a 2x2 grid.&quot;,        ///		Depen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shiftorium {
            get {
                return ResourceManager.GetString("Shiftorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///]
        ///.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {        ///	&quot;{SUBMIT}&quot;:&quot;Bestätigen&quot;,        ///        ///&quot;{TERMINAL_TUTORIAL_1}&quot;:&quot;Wilkommen zum Plex Terminal. Hier wirst du die meiste Zeit in Plex verbringen.        ///          ///Eine kurze Erklärung wie du das Terminal benutzt lautet wiefolgt. Du kannst das command &apos;sos.help&apos; benutzen um eine Liste aller commands aufzurufen. Schreib es        ///einfach in das Terminal und drücke &lt;enter&gt; um alle commands anzuzeigen.        ///         ///Commands können mit argumenten versehen werden, indem du ein key-value Paar in einem {} Block hinter dem command angibst. Zum Beispiel:        ///         ///some [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_de {
            get {
                return ResourceManager.GetString("strings_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {        ///	&quot;{SUBMIT}&quot;:&quot;Submit&quot;,        ///        ///&quot;{TERMINAL_TUTORIAL_1}&quot;:&quot;Welcome to the Plex terminal. This is where you will spend the bulk of your time within Plex.        ///	        ///A brief rundown of how to use the terminal is as follows. You can use the &apos;sos.help&apos; command to show a list of all commands. Simply type it in and strike &lt;enter&gt; to view all commands.        ///	        ///Commands can be sent arguments by specifying a key-value pair inside a {} block at the end of the command. For example:        ///	        ///some.command{print:\&quot;hello\&quot;}        ///math.add{op1:1,op2:2}        ///set.va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_en {
            get {
                return ResourceManager.GetString("strings_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;{SUBMIT}&quot;:&quot;You as a homo sapien are going to perform an action where you confirm what you have said&quot;,
        ///
        ///&quot;{TERMINAL_TUTORIAL_1}&quot;:&quot;Welcome to the ShiftOS terminal. This is where you will spend the bulk of your time within ShiftOS.
        ///	
        ///A brief rundown of how to use the terminal is as follows. You can use the &apos;sos.help&apos; command to show a list of all commands. Simply type it in and strike &lt;enter&gt; to view all commands.
        ///	
        ///Commands can be sent arguments by specifying a key-value pair inside a {} block at th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_ver {
            get {
                return ResourceManager.GetString("strings_ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {        ///	Character: &quot;sys&quot;,        ///	Lines:[        ///		&quot;Hello there, %user.&quot;,        ///		&quot;Welcome to Plex.&quot;,        ///		&quot;This is an automated message to all new sentiences within the Plex multi-user domain.&quot;,        ///		&quot;Before you can begin with Plex, you&apos;ll need to know a few things about it.&quot;,        ///		&quot;One: Terminal command syntax.&quot;,        ///		&quot;Inside Plex, the bulk of your time is going to be spent within the Terminal.&quot;,        ///		&quot;The Terminal is an application that starts up when you turn on your computer. It allows you to execute system commands, open programs and contro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sys_shiftoriumstory {
            get {
                return ResourceManager.GetString("sys_shiftoriumstory", resourceCulture);
            }
        }
    }
}
